### ISSUE TITLE
Component Procurement

### ISSUE THREAD

**Issue by David-Shang** [bellabaohaha/CITS5206-Gp2#33]
Get components for the IoT prototype and gateway system, consult Atif/Andrew Burrell.

**Comment by asadmaza** [comment]
Off the back of our meeting with Atif and Gustavo

![image](https://github.com/user-attachments/assets/10674222-5fa9-463e-a1ae-aa2d31c76454)


We may not need to get the components but identification will be important I imagine.

**Comment by bellabaohaha** [comment]
- I did some research and I found some device that provides multiple depth monitor. (https://hydroterra.com.au/product/sentek-enviroscan-soil-moisture-probe/ ) However this device seems expensive. The sensor node should be lightweight, power-efficient, and low-cost. For cost efficiency I suggest we use the current ones and manually insert into different depth.

- Dr. Omar suggested to use a proper solar panel for the power. However the implementation of solar panel depends on farm so I suggest we go with safety choice battery. 
- As Dr. Omar mentioned, GPS modules are power-intensive, so it's better to record the sensor location at deployment rather than using a dedicated GPS module continuously. I deleted the GPS module required in our original list. Instead we will manually record the coordinate. 
- If below components are fine, we can email client and get the component this Friday. 
<img width="931" alt="WechatIMG747" src="https://github.com/user-attachments/assets/d33c92f0-49f3-4bfb-9e4e-9b2e7013dff4">

**Comment by asadmaza** [comment]
GPS module is inbuilt in the TTGO T-Beam.

I think a better solution than deleting it would be to:

Have a deployment set of code where the GPS location is received on initial setup.

Another set of code that gets sensor readings and puts board to sleep.

Very similar to initial Setup and void infinite loops as you have in most IoT programs.

That way we only get location once instead.

**Comment by asadmaza** [comment]
See these links about turning off GPS on T-Beam to save power after getting it once and only once on deployment:

https://meshtastic.org/docs/hardware/devices/tbeam/buttons/ - Hardware method

https://github.com/LilyGO/TTGO-T-Beam/issues/19 - SDK/Programmatic method

**Comment by bellabaohaha** [comment]
![Image](https://github.com/user-attachments/assets/ab86ba19-45c9-4478-8149-1705878aa5c1)

**Comment by asadmaza** [comment]
FYI I gathered and gave the components to the team yesterday and have emailed Andy.

Please go through the sensors that Gustavo has sent via email.

I spoke with Atif yesterday and he also recommended this paper:
https://www.researchgate.net/publication/372604305_Evaluation_of_Three_Soil_Moisture_Profile_Sensors_Using_Laboratory_and_Field_Experiments

See what works with our constraints, just had a quick look at your constraints, some feedback: we don't need to power it via the TTGO (5V/3.3V), it could have its own power delivery, as long as we can communicate with the TTGO.

**Comment by bellabaohaha** [comment]
Summary of the sensors video sent by client Gustavo: 

There are many types of moisture sensors in the market to choose from. In the video, the speaker Troy Peters provides an overview of various soil moisture sensors used in agriculture, focusing on their operational mechanisms and suitability for irrigation management. The neutron probe is considered the gold standard for measuring soil moisture. It works by emitting neutrons from a radioactive source, which interact with hydrogen atoms in the soil to give an accurate reading of water content. Despite its accuracy and ability to sample large areas, neutron probes are costly, involve radioactive materials, and require manual handling, which limits their widespread use among farmers.

The tensiometer measures soil water tension, which is the force plants need to exert to extract water from the soil. This tool is affordable and easy to use, providing a direct indication of when irrigation is needed. However, it only measures a small area and does not provide information on how much water to apply. The sensor is less suitable for determining precise water volumes but can be very helpful in monitoring when plants begin to experience water stress.

Resistance sensors, widely used due to their affordability, measure soil moisture by detecting electrical resistance between conductors in a gypsum block. These sensors provide trends in soil water potential, which can be useful for irrigation scheduling. However, they can degrade over time and are affected by salinity and soil structure, making them less reliable in certain conditions. Their low power consumption and ability to log data continuously make them popular for longer-term field use.

The capacitance sensor measures soil’s ability to hold an electric charge between two conductors, giving an estimate of the soil water content. These sensors are sensitive to installation and soil structure, but they offer ease of use through data logging and automation. They are particularly effective in sandy soils, though they can be influenced by soil salinity and temperature. 

Another technology, time domain reflectometry (TDR), works by sending an electric pulse to measure the soil’s dielectric properties. It provides a broader measurement area and is less sensitive to soil inconsistencies than capacitance sensors, though it requires more sophisticated electronics and energy to operate.
