### ISSUE TITLE
Soil Moisture Sensor Integration

### ISSUE THREAD

**Issue by David-Shang** [bellabaohaha/CITS5206-Gp2#34]
Integrate the soil moisture sensors with the TTGO T-Beam microcontroller, test, and calibrate.

**Comment by dharaninagala** [comment]
# Soil Moisture Monitoring with TTGO T-Beam - Completed

The integration of the soil moisture sensors with the TTGO T-Beam is successfully completed. All components are working as expected, with accurate sensor readings. Calibration of the sensor for dry and wet conditions has been performed, and the firmware is working fine. Testing across different soil conditions shows consistent results.

**Comment by dharaninagala** [comment]
**Measuring Soil Moisture Readings:**

Soil moisture levels at depths of 10 cm, 20 cm, and 30 cm can be measured using capacitive sensors connected to the TTGO T-Beam. Each sensor is accessed by the following pins: Pin 14 (10 cm), Pin 13 (20 cm), and Pin 15 (30 cm). The analogRead() function reads unprocessed sensor readings, thereafter transformed into moisture percentages via the map() function. The mapping converts measurements to a scale ranging from 0% (dry) to 100% (wet), by using established wet and dry reference values. The results are presented in a readable format and displayed with a 3-second interval between readings for stability.

Code snippet:

![Image](https://github.com/user-attachments/assets/95cbcf29-2edb-4e42-ad28-fcaaae26f46d)


**Error Correction:** 

The sensor which we are using in this project is of basic version and not that accurate, sometimes it gives a weird readings when measured in different conditions and if that values are used to calculate the percentage of soil moisture, the percentage would not be in proper format.So to take that outlier values out of consideration,  if any sensor reading is less or greater than of constant wet/dry values, that difference of the value should be added or removed to make that sensor value comes under acceptable range which then gives us correct moisture percentage reading.

**Error Correction Logic:**
The sensors might give readings that aren't in the calibrated range due to incorrect moisture percentage readings or to environmental factors. To fix these outliers:
Each sensor reading is compared to the calibrated wet and dry constants in the code once the sensor readings are read from the analogue pins. 
**For Lower bound check:** 
• If the sensorReading is less than the constant wet value (which represents the minimum calibrated value), it is set equal to wet.
**For Upper bound check:**
• If the sensorReading is greater than the constant dry value (which represents the maximum calibrated value), it is set equal to dry.

Code snippet:
![Image](https://github.com/user-attachments/assets/eb8fe08b-7869-4c09-8a91-5b209c649cf8)


![Image](https://github.com/user-attachments/assets/9999630f-c2f0-498e-b463-223d9f41f6c8)


Output:
When the updated code is uploaded to the system and tested under both wet and dry conditions, the implemented error correction logic effectively excludes outlier values from the sensor readings. This ensures that the soil moisture readings and the calculated moisture percentages remain within acceptable ranges, providing accurate and reliable measurements.

![Image](https://github.com/user-attachments/assets/7ee42153-9ccc-40cb-bee0-fcf400f905cd)

![Image](https://github.com/user-attachments/assets/8f3aa305-270b-4cdd-a23a-2cd99c3c88e8)

![Image](https://github.com/user-attachments/assets/122e1397-dcb9-4c37-8b63-b7e9ed8b3d3d)

![Image](https://github.com/user-attachments/assets/0350eca4-61ef-4348-a2a8-ac35aab01358)

**Comment by dharaninagala** [comment]
Calibration Steps:

1. Preparation of Dry Soil Sample
Step 1: Used a glass container with dry loam soil. Ensured the soil is completely dry and free from moisture.
Step 2: Labelled the sensors as Sensor 1, Sensor 2, and Sensor 3 for identification.

2. Dry Condition Calibration
 For Each Sensor (Repeat Steps Below for Sensors 1, 2, and 3):
a. Inserted the sensor into the dry soil at the first position.
• Recorded the reading as DryValue1.
b. Removed and wiped the sensor with a piece of cloth and reinserted the sensor into a different position in the soil.
• Recorded the reading as DryValue2.
c. Repeated once more for a third position.
• Recorded the reading as DryValue3.
d. Calculated the average of DryValue1, DryValue2, and DryValue3.
• This average is the Dry Value for that sensor.

3. Preparation of Wet Soil Sample
Step 1: Measured 100ml of water using the measuring cup.
Step 2: Poured the water evenly into the loam soil in the glass container.
Step 3: Mixed the soil thoroughly to ensure uniform moisture throughout.

4. Wet Condition Calibration
For Each Sensor (Repeat Steps Below for Sensors 1, 2, and 3):
a. Inserted the sensor into the wet soil at the first position.
•Recorded the reading as WetValue1.
b. Remove and wipe the sensor with a piece of cloth and reinsert the sensor into a different position in the wet soil.
•Recorded the reading as WetValue2.
c. Repeated once more for a third position.
•Recorded the reading as WetValue3.
d. Calculated the average of WetValue1, WetValue2, and WetValue3.
• This average is the Wet Value for that sensor.

5. Recording Calibration Data
Step 1: Organized all recorded values in a spreadsheet or table for clarity.
Step 2: Documented the Average Dry Value and Average Wet Value for each sensor.
Step 3: These values will serve as reference points in the code's map() function to convert raw readings into percentage moisture levels.

The sensor readings are obtained by reading the value from the analog pins where each sensor is connected. These sensor values are converted into percentage by using a map function with the help of constant wet and dry values.
The Constant Wet and Dry Values are derived by calibrating the sensors in dry and wet conditions are formulated as below:
​​
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>

<meta http-equiv="Content-Style-Type" content="text/css">
<title></title>
<meta name="Generator" content="Cocoa HTML Writer">
<meta name="CocoaVersion" content="2487.3">
<style type="text/css">
p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; text-align: justify; font: 13.0px '.AppleSystemUIFont'}
table.t1 {border-collapse: collapse}
td.td1 {border-style: solid; border-width: 1.0px 1.0px 1.0px 1.0px; border-color: #9a9a9a #9a9a9a #9a9a9a #9a9a9a; padding: 1.0px 5.0px 1.0px 5.0px}
</style>
</head>
<body>

Sensor | Soil Moisture Sensor1 | Soil Moisture Sensor2 | Soil Moisture Sensor3
-- | -- | -- | --
DryValue1 | 2744 | 2775 | 2749
DryValue2 | 2749 | 2719 | 2657
DryValue3 | 2768 | 2755 | 2683
WetValue1 | 1463 | 1453 | 1482
WetValue2 | 1467 | 1467 | 1487
WetValue3 | 1498 | 1499 | 1520
DryAverage | 2754 | 2750 | 2696
WetAverage | 1476 | 1473 | 1496


</body>
</html>

Table. Sensor values under dry and wet conditions


Note: Here the calibration of range of values for wet and dry conditions are done in one type of soil that is Loam soil. Western Australia contains different types of soil, Hence the values may vary if tested in different types of soil.
And based on the accuracy of the sensors that are used the values may also vary.
