### ISSUE TITLE
Cloud Storage Setup (AWS IoT Core & DynamoDB)

### ISSUE THREAD

**Issue by David-Shang** [bellabaohaha/CITS5206-Gp2#38]
Set up AWS IoT Core and DynamoDB to store the transmitted data from the gateway.

**Comment by asadmaza** [comment]
As per our discussion with Yanchen, I'm uploading the information for how I achieved this task on the AWS account.

I suggested to David to use a convention and abstract away non-dynamic information (i.e. static information that are typical of key value pairs with repeated keys every time.). This is because he said that the payload would not deliver and the payload packet size was too large. As we are following convention, and have abstracted away some repetitive data. As the keys do not change, only the values change, hence, not only do I need to store the information in DynamoDB for AWS QuickSights, but I also need to transform the data and add the missing key information back in and ensure that it's stored properly in DynamoDB. I followed the process below, I've attached some proof as AWS is closed source. If teaching staff need access to AWS I'm happy to provide ReadOnlyAccess.

1. **Created DynamoDB table:**
  - I logged into the **AWS Management Console**.
  - Created the table `SoilMoistureData` with Partition key `gateway_id` and Sort key `sensor_board_id_timestamp`
  - Used default Read/Write Units and autoscaling
   **Screenshot of table creation:**
![Image](https://github.com/user-attachments/assets/ff3eae14-699c-42df-a889-55673be8d5bf)

2. **Create AWS Lambda Function:**
   - I navigated to the **AWS Lambda** Console and created a new Lambda function.
   - I named the function `ProcessSoilMoistureData` and selected Python 3.12 as the runtime and x86_64 architecture.
   - I attached AWS managed DynamoDB full access role for **DynamoDB write permissions** for `ProcessSoilMoistureData` Lambda function.
   - I then crafted my Lambda function code that processes the incoming IoT message and writes it to DynamoDB:
```python
'''
Lambda function is responsible for:
- Extracting and transforming message delivered to AWS IoT Core topic from the Internet Gateway Master Node
- Create item into DynamoDb Table called `SoilMoistureData` with the transformed message
- Error handling with appropriate messages for:
    Invalid paylod structure in AWS IoT Core Topic
    DynamoDB Write Errors
    Missing/Incorrect Data
    Catch all (Unexpected exceptions)

Developed by Asad Maza
v1.0
'''

# Import necessary libraries
import json
import boto3
import logging

# Start DynamoDB and Logger
dynamodb = boto3.resource('dynamodb')
table = dynamodb.Table('SoilMoistureData')
logger = logging.getLogger()
logger.setLevel(logging.INFO)

def lambda_handler(event, context):
    try:
        # Log event for debugging
        logger.info(f"Received event: {json.dumps(event)}")

        # Use event as message
        message = event
        logger.info(f"Parsed Message: {message}")
        
        # Validate message is a list
        if not isinstance(message, list):
            logger.error("Invalid message format: Expected a list.")
            return {
                'statusCode': 400,
                'body': json.dumps('Error: Invalid message format. Expected a list.')
            }
        
        # Validate message length (Expected 16 fields: 5 sensor data, 6 alternating sensor depth/moisture, 5 gateway data)
        if len(message) != 16:
            logger.error(f"Malformed message: expected 16 fields, got {len(message)} fields.")
            return {
                'statusCode': 400,
                'body': json.dumps(f'Error: Malformed message. Expected exactly 16 fields, got {len(message)}.')
            }

        # Parse sensor board data (first 5 values)
        sensor_board_id = message[0]
        sensor_board_date = message[1]
        sensor_board_time = message[2]
        sensor_board_coordinates = message[3]  # Currently not split coordinates
        sensor_board_battery = message[4]
        
        # Parse sensor readings (alternating sensor depths and moisture levels)
        depth_values = message[5:10:2]  # Extracts 1st, 3rd, and 5th numbers as depths (sensor depths)
        soil_moisture_levels = message[6:11:2]  # Extracts 2nd, 4th, and 6th numbers as moisture levels
        
        # Map depths to their corresponding moisture levels
        moisture_data = {f"{depth}cm": f"{moisture_level}%" for depth, moisture_level in zip(depth_values, soil_moisture_levels)}
        
        # Parse gateway board data (last 5 values)
        gateway_id = message[11]  # Gateway ID
        gateway_date = message[12]
        gateway_time = message[13]
        gateway_coordinates = message[14]  # Do not split coordinates
        gateway_battery = message[15]  # Gateway Battery

        # Combine sensor board date and time for sensor timestamp
        sensor_timestamp = f"{sensor_board_date}T{sensor_board_time}"
        
        # Combine gateway date and time for gateway timestamp
        gateway_timestamp = f"{gateway_date}T{gateway_time}"
        
        # Prepare item to insert into DynamoDB
        item = {
            'gateway_id': str(gateway_id),  # Ensure this is stored as a string
            'sensor_board_id_timestamp': f"{sensor_board_id}_{sensor_timestamp}",
            'gateway_time': gateway_timestamp,
            'gateway_battery': gateway_battery,
            'gateway_location': gateway_coordinates,  # Store as a single string
            'sensor_board_location': sensor_board_coordinates,  # Store as a single string
            'sensor_board_battery': sensor_board_battery,
            'moisture_data': moisture_data
        }

        # Log item to be inserted (for debugging)
        logger.info(f"Inserting item into DynamoDB: {json.dumps(item)}")

        # Attempt to insert item into DynamoDB
        try:
            table.put_item(Item=item)
        except Exception as e:
            logger.error(f"DynamoDB put_item error: {e}")
            return {
                'statusCode': 500,
                'body': json.dumps(f'Error: Unable to insert data into DynamoDB. {str(e)}')
            }
        
        # Success response
        return {
            'statusCode': 200,
            'body': json.dumps('Data successfully saved to DynamoDB!')
        }

    except json.JSONDecodeError as e:
        # Handle JSON parsing error
        logger.error(f"JSON decoding failed: {e}")
        return {
                'statusCode': 400,
                'body': json.dumps('Error: Invalid JSON format.')
        }
    except Exception as e:
        # Catch all for unexpected errors
        logger.error(f"Unexpected error: {e}")
        return {
            'statusCode': 500,
            'body': json.dumps(f'Error: {str(e)}')
        }
```

**Screenshot of Lambda Function Setup:**
![Image](https://github.com/user-attachments/assets/02a7fea8-fb05-4e89-b97f-0a60d93d13ed)

**Screenshot of Created Lambda Function Role:**
![Image](https://github.com/user-attachments/assets/698934ce-21c0-4d4b-868b-a98cdff77fca)

**Screenshot of Created Lambda Function Policy for Creating Log Group and Full Access to DynamoDB:**
![Image](https://github.com/user-attachments/assets/97f7c442-826d-4aa8-a775-62e76b68761d)


3. **Created an AWS IoT Rule to Trigger Lambda:**
   - Under the **Message Routing** -> **Rules** section, I created a new rule to listen to the topic `esp32/pub`.
   - I set the SQL query as:  
     ```sql
     SELECT * FROM 'esp32/pub'
     ```
   - I added an action to invoke a **Lambda function** and selected the Lambda function I would create for processing the data.

**Screenshot of AWS IoT Rule Created:**
![Image](https://github.com/user-attachments/assets/0922f5d2-c72c-49de-83e3-1b4fe0e4bde6)


3. **Setup DynamoDB Table:**
   - I went to the **AWS DynamoDB** and created a new table called `SoilMoistureData`.
   - I set the partition key to `gateway_id` (String) and the Sort key to `sensor_board_id_timestamp` (String).

   **Screenshot showing DynamoDB table schema with keys:**
![Image](https://github.com/user-attachments/assets/b505c51b-7399-496d-bf9b-f91d7db69ee2)


4. **Tested the IoT to Lambda to DynamoDB Data Flow:**
   - In **AWS IoT Core**, I clicked on *MQTT Test Client**  option in the **Test** Section.
   - I published a test message to the topic `esp32/pub` with the following payload (array):
     ```json
     [
       "sb11",
       "2024-09-12",
       "12:34:56", 
       "51.5074, 0.1278", 
       "75%",
       10, 
       15, 
       20, 
       25, 
       30, 
       50,
       "gt1", 
       "2024-09-12", 
       "12:34:56", 
       "51.5074, 0.1278", 
       "80%"
     ]
     ```
   - I verified that Lambda function was triggered and successfully processed the message.

   **Screenshot showing IoT Publish to `esp32/pub` test:**
![Image](https://github.com/user-attachments/assets/cae1a6fa-2d32-43b1-8118-f65943c3f622)

**Screenshot showing Lambda Function execution:**
![Image](https://github.com/user-attachments/assets/0c3a471c-fc42-419a-9415-6942d6658dbe)

5. **Verify Data Inserted Successfully in DynamoDB:**
   - I opened **AWS DynamoDB** and explored `SoilMoistureData` table to check if data was correctly inserted.
   - I verified that the data all correctly mapped as expected, after transformation, this is what was stored in DynamoDB (JSON):
```json
     {
  "gateway_id": {
    "S": "gt1"
  },
  "sensor_board_id_timestamp": {
    "S": "sb11_2024-09-12T12:34:56"
  },
  "gateway_battery": {
    "S": "80%"
  },
  "gateway_location": {
    "S": "51.5074, 0.1278"
  },
  "gateway_time": {
    "S": "2024-09-12T12:34:56"
  },
  "moisture_data": {
    "M": {
      "10cm": {
        "S": "15%"
      },
      "20cm": {
        "S": "25%"
      },
      "30cm": {
        "S": "50%"
      }
    }
  },
  "sensor_board_battery": {
    "S": "75%"
  },
  "sensor_board_location": {
    "S": "51.5074, 0.1278"
  }
}
```
   **Screenshot showing data stored in DynamoDB after processing:**
![Image](https://github.com/user-attachments/assets/ca7b3e4e-83a4-404f-833f-0531d15e5e75)


6. **Checked Logs in CloudWatch:**
   - I also went to **AWS CloudWatch** to check the logs for the Lambda function.
   - I reviewed log group `/aws/lambda/ProcessSoilMoistureData` to ensure there were no errors and that the function processed the message as expected.

   **Screenshot showing CloudWatch logs with Lambda Function Execution Details:**
![Image](https://github.com/user-attachments/assets/4c3e0e4a-d3ac-4409-8b75-a0a4ecac2b5e)

**Comment by asadmaza** [comment]
Closing again, see [Pull Request #48 ](https://github.com/bellabaohaha/CITS5206-Gp2/pull/48) for code review process.

**Comment by bellabaohaha** [comment]
Based on Asad's work above, I downloaded data from AWS CloudWatch and cleaned it. It is then transformed into a JSON file to be uploaded to DynamoDB. By importing the dataset from DynamoDB to the AWS Quicksight, I am able to visualise it by creating a table visual to demonstrate the test data.
