### ISSUE TITLE
Develop Visualization Dashboard (Priority 1)

### ISSUE THREAD

**Issue by David-Shang** [bellabaohaha/CITS5206-Gp2#39]
Priority 1: Create a basic visualization dashboard using AWS QuickSight.

Priority 2: Send data to the John Deere Platform using Assets API.

**Comment by bellabaohaha** [comment]
What to contain in the QuickSight interface: 

> a map or list that displays all sensors and their individual moisture levels.
> 
> Display of current soil moisture levels in percentage with a simple visual format (e.g., dry, optimal, wet).
> 
> A graphical trend or history of moisture levels over time, allowing users to track changes. Clear, easy-to-understand icons and color coding (e.g., green for optimal moisture, red for too dry/wet). 
> 
> Enable users to customize and select sensor & time period 
> 
> Threshold settings for moisture levels where users can set limits (e.g., below 30% triggers "dry" warning).
> 
> Watering recommendations based on current moisture levels and trends (e.g., "Water in 2 days").

> Optional:
> *Graphs that compare moisture levels with other environmental data like rainfall or temperature. (Need to import weather API)
> 
> *Current weather data and forecast integration to help users anticipate moisture needs based on expected rainfall.
> 
> *Mobile-friendly, responsive design for ease of access on different devices.

**Comment by bellabaohaha** [comment]
![Image](https://github.com/user-attachments/assets/fc5994ab-68f9-4381-a1d7-2f64bb4ac91d)

Version1.0 of the interface using AWS quicksight with mock data.

It has 3 parts in the interface:

> A map  that displays all sensors locations
> 
> Display of current soil moisture levels in percentage.
> 
> A graphical trend or history of moisture levels over time, allowing users to track changes with 2 Thresholds for max/min moisture levels.

Next step we will consult Gustavo of the comments and feedback for this prototype version. 
Also we will refine the interface and add more features.

**Comment by bellabaohaha** [comment]
Received feedback from client stating it is good. 
I added our UWA logo and battery level as well.
![image](https://github.com/user-attachments/assets/1d399c7a-ca4b-4b5f-9238-6283391f1987)

**Comment by bellabaohaha** [comment]
- Update AWS DynamoDB for latest dataset
- Update dashboard: 
1. Only show battery visual when battery <20%:
 ifelse(
{sensor_board_battery_percentage} >20 ,"Battery good",
{sensor_board_battery_percentage}<=20, "Battery low only {sensor_board_battery_percentage}",
"no data"
)
2. Add a card to show message under different conditions: moisture level >40 and <=40 
3. Update the gauge chart to show icon and change color under different moisture level 
4. Add a table for testing data(to be updated once testing data finalized to dynamoDB)

![image](https://github.com/user-attachments/assets/765e343a-cd3d-4590-b6f5-af9c5fdc4514)

**Comment by bellabaohaha** [comment]
**Step 1 Visualization Selection**  
Various types of visuals are selected to present the report for best effects. A gauge chart is selected to display soil moisture level in a simple and intuitive format. It effectively displays real-time status information, such as whether the soil moisture is within the desired range, enabling users to quickly assess current conditions.
 
<img width="416" alt="image" src="https://github.com/user-attachments/assets/6e63e0d5-d3f4-4bb9-bbe8-a61bda98d812">

A line chart is selected to display historical trends in soil moisture. The x axis is a sensor timestamp by ascending order. It shows four lines indicating moisture levels of different depths and an average moisture level. It allows users to track changes over time and to help them make data-driven decisions about irrigation. The inclusion of threshold lines for the lowest acceptable moisture levels adds clarity, ensuring users can easily determine whether moisture levels are within ideal range.
 
<img width="363" alt="image" src="https://github.com/user-attachments/assets/5b1d660b-74b8-47a1-91fa-a3dab39efc7d">
 
<img width="416" alt="image" src="https://github.com/user-attachments/assets/6f28cc36-0afd-4c9c-b06c-2415069b51f7">

Geospatial maps were included to visualize the locations of different sensor boards and gateways. This is particularly useful in understanding how moisture levels vary across different areas of the monitored field.
 
<img width="416" alt="image" src="https://github.com/user-attachments/assets/612f2cb3-a602-4df2-a934-14b78b582d8f">
 
<img width="295" alt="image" src="https://github.com/user-attachments/assets/9f679b17-efe3-4046-b166-1cccefeb4652">
 
 

**Step 2 Adding Calculated Fields**
As the imported data is raw, calculated fields are created in the dashboard for visualisation, such as, average moisture level, battery warning, and moisture warning. The calculated fields are created using syntax of AWS QuickSight, for example, to get average moisture level we use below syntax:
 
({sensor_board_depth1_soil_moisture_percentage}+{sensor_board_depth2_soil_moisture_percentage}+{sensor_board_depth3_soil_moisture_percentage})/3
 
<img width="416" alt="image" src="https://github.com/user-attachments/assets/bb2ac345-dc47-4437-b68c-8e9fcf2a503c">

With this calculated field of average moisture level, we can apply this measure to a line chart to show the historical trend of average moisture level calculated from all the sensors of various depths.
 
We also added a calculated field for battery level to enable this show up only when the battery is less than 20%. Since the battery level does not fluctuate significantly over time, it doesn’t need to be displayed constantly.
 
ifelse(
{sensor_board_battery_percentage} >20, "Battery Good",
{sensor_board_battery_percentage}<=20, "Battery low only {sensor_board_battery_percentage}. Need to replace battery.",
NULL
)
 
<img width="416" alt="image" src="https://github.com/user-attachments/assets/72acb05b-ee42-4cf9-b4ef-b81578112026">


**Step 3 Conditional Formatting**
To enhance the visualization for users to interpret, conditional formatting is implemented with different message, icons, and color of text. For example, the syntax for displaying different messages under different moisture level as below for the calculated field moisture_warning:
 
ifelse({average_moisture_level} >= 80, "Soil moisture is too high. Avoid farming operations until the water level subsides to prevent crop damage.",
{average_moisture_level}> 40 AND {average_moisture_level} < 80, "Soil moisture is optimal. No irrigation required.",
{average_moisture_level} <= 40, "Soil moisture is low. Irrigation needed. You can start watering and proceed with your farming tasks.",
"NULL"
)
 
<img width="416" alt="image" src="https://github.com/user-attachments/assets/30b7d4ba-4c0f-4267-93b8-07494863238b">

It shows 3 different messages to indicate the aggregated moisture level is too wet, perfect, or too dry with different colors and icons. Here the threholds are set as 3: moisture level% >=80% as too wet, 40% < moisture level% < 80% as perfect, moisture level% <= 40% as too dry. The color of text and icon conditional formatting as below:
 
<img width="269" alt="image" src="https://github.com/user-attachments/assets/ab4375dc-1033-4a39-aa96-636c3c2d3e5d">

Here is how this visual would look like in different moisture level:
 
<img width="416" alt="image" src="https://github.com/user-attachments/assets/090b8599-fdbf-4442-8a8c-4ae10d12c14f">

We implemented a card for battery information and applied conditional formatting, so it only appears a warning when the battery level drops below 20%. Other times, this card is hidden. It is in the left bottom in the dashboard.
<img width="180" alt="image" src="https://github.com/user-attachments/assets/d2b01614-bdb2-49c4-8434-ddd8dd36510d">
<img width="367" alt="image" src="https://github.com/user-attachments/assets/548bbd1c-b180-43ca-bcfe-101ee6c341b0">

 **Step 4 User-Customizable Features**
Each visual is edited with a title to make it more understandable. For the moisture level historical line chart, two reference lines are added to demonstrate the highest and lowest moisture level thresholds, which can be customized by users.    
 
This dashboard also allows users to filter the data by sensors, gateways, and timestamp. For example, when a user would like to see the latest reading, they can filter by timestamp to keep the latest reading only. The filter can be applied to a single visual or the entire dashboard, and the visuals will be updated accordingly.
 
<img width="319" alt="image" src="https://github.com/user-attachments/assets/aff4226f-5245-409d-bfff-cfaf1ed6d3ff">
For example, here we select only the latest reading to filter and apply to the gauge chart. It would show this specific reading only. This provides users to get to know the data they need with convenience.
 
<img width="416" alt="image" src="https://github.com/user-attachments/assets/f5d41420-f381-4c60-aae9-cb1378dc4eeb">

**Comment by asadmaza** [comment]
Closing as work has been completed.
