### ISSUE TITLE
Final Presentation and Handover

### ISSUE THREAD

**Issue by David-Shang** [bellabaohaha/CITS5206-Gp2#42]
Present the final solution to stakeholders and complete the handover.

**Comment by asadmaza** [comment]
We had our draft presentation on Friday 04th October where client provided feedback on our soil moisture sensor system, internet gateway and dashboard. For details on the meeting and next steps please refer to Client Meetings.

**Comment by asadmaza** [comment]
We had our second presentation on Friday 11th October at 10AM with Atif as Gustavo could not make it. We recorded it on teams however the recording was done in CSSE Lab 2.07 with the video conferencing teams software. I launched INC0894338 on UWA IT Service desk however they haven't responded.

Since then I have sent an email to Gustavo as per image below with all the details/summary of the meeting:
![Image](https://github.com/user-attachments/assets/09c5c02d-81db-43c8-b389-4d0a3de30431)


Adding in Hyper links from the email:
1. [API Docs for Historical Weather Data](https://open-meteo.com/en/docs/historical-forecast-api#hourly=temperature_2m,direct_radiation)
2. [Example of Detailed Github Project Task Steps](https://github.com/bellabaohaha/CITS5206-Gp2/issues/38)


I am going to create AWS read only accounts for Atif and Gustavo which I will then deprovision in a month in case they want to see how something is setup. I will send them an email today.
